### ISSUE TITLE
Repo Support Status?

### ISSUE THREAD

**Issue by Simonl9l** [OmniSharp/csharp-language-server-protocol#1221]
Inquiring minds!

Given the significant C# change to no longer use OmniSharp for the C# VSCode experience, beyond Omnisharp being used in [bicep](https://github.com/Azure/bicep/tree/main/src/Bicep.LangServer), what is the real drivers to ensure this repo continues to be maintained.

For others that have built C# based LPS's using OmniSharp, this is critical, as for C# there are limited alternatives.

It can be [observed](https://github.com/OmniSharp/csharp-language-server-protocol/pulls) that there are a number of chore pull requests for version bumps that have not been merged. 

There are also a number of [issues](https://github.com/OmniSharp/csharp-language-server-protocol/issues) that have gone unanswered.

It seem at this point this repo is not even in "Support Mode"?  It would be great the maintainer could updated the status [here](https://github.com/OmniSharp/OmniSharp).

Also it seem there was a plan to migrate this set of repos to .Net Foundation support as indicated on the [communications](https://github.com/OmniSharp/OmniSharp) page, but this [issue](https://github.com/OmniSharp/OmniSharp/issues/22) set to show this is still a work in progress.

**Comment by andyleejordan** [comment]
I would also like to know, as the maintainer of the [PowerShell Extension for VS Code](https://github.com/PowerShell/vscode-powershell) I'm completely dependent on this project, since our [LSP Server](https://github.com/PowerShell/PowerShellEditorServices) is implemented on top of it. We have half a million monthly active users so it's _definitely_ in use and depended on.

**Comment by JoeRobich** [comment]
Thanks for asking these questions. There is certainly a need for developers with time to contribute to these projects.

As a maintainer for the 1.x C# extension for VS Code, I contributed to OmniSharp-Roslyn (O#) and want to see it continue to be useful to the community. I've made an effort to contribute to this repo in order to light up new functionality in O#, but free time comes and goes.

I would say that O#'s goal is to remain an open-source, community-led C# Language Server. Which nowadays means having robust LSP support. If anyone has used O# in LSP mode within the VS Code C# extension, you will know that we are a ways away from that goal.

With that being said, I think the real value to the community is in having the O# Language Server not so much the LSP library. If the Roslyn team were to announce that their [CLaSP library](https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/README.md) was supported, then I think we would need to consider moving O# to it in order to reduce the maintenance burden.

Having just moved back to the Roslyn team, I expect that I'll have a little more time to look at issues in O# and this repo, since my work life will be a bit more aligned with this work. However, I cannot commit myself to fixing issues that do not immediately impact or hinder O# running in VS Code.

**Comment by JoeRobich** [comment]
@Simonl9l Do you think there have been enough changes to warrant a new release? If so, I can try and get one out next week.

**Comment by CppCXY** [comment]
> As noted before - Beyond dependency fixes is there any planned functions milestones - given either updates to the spec(?) or leveraging underlying technical advances with say new .Net/C# versions. [Code Gen Serialization](https://github.com/OmniSharp/csharp-language-server-protocol/issues/150) (than NewtonSoft) and that underlying tech for general reflection elimination would be great (I see there is some code gen in the project), such that at some point it becomes AoT-able.
> 
> The value prop here is two fold:
> 
> 1. AoT allows for general performance improvement and compiled & trimmed machine code file size.
> 2. If we leverage an underlying compiler with his framework to get our LSP implementation functional, having that code AoT'd make is far harder for that to be reverse engineered - than from an IL Decompile.
> 
> There is hope since you are around...and hope that it not just you, and anything you can do to keep it supportable is greatly appreciated - thanks!

Refactoring to support AOT is very time-consuming. I worked continuously for a week to initially achieve AOT support for the protocol. Additionally, removing reflection-based libraries might change the way you write code, making it unlikely to seamlessly upgrade to an AOT-supported version. If you want AOT support, I recommend directly using my library, which has been released and running well for a long time. If Omnisharp plans to support AOT, I support reusing the protocol code from my repository.

**Comment by CppCXY** [comment]
> @CppCXY is you library a derivative work of this project - and you are also a maintainer here?

No, I completely redeveloped it. However, I was a user of O# before, and I discovered that the library had memory leaks. It was difficult for me to fix the library, so I redeveloped a clean, dependency-free library (you will find that I don't rely on any third-party NuGet packages when you open the project).
> 
> I fully understand what you are saying - is you library functionally (per spec) as feature complete as this one? What is the migration path? I see very little in the way of documentation on how to use it, the Test example is very limited.

I implemented the specification step by step according to the documentation up to version 3.18. Due to limited manpower, there might be some omissions, but they do not affect usage.
> 
> I used the bicep LSP implementation that uses O# for much inspiration.
> 
> It seems there are few C# options in the LSP server space and wisdom of crowds goes a long way!
> 

My test case is a language server that implements most of the useful features and can be directly AOT compiled. If the test case is not sufficient, I also have a real-world language server that uses AOT compilation.
> If there is a way to port what you have done into this larger ecosystem it seems there would be value.

O# heavily relies on Newtonsoft and other reflection-based libraries. Porting it over would likely change the way code is written, making it not a smooth upgrade.

**Comment by CppCXY** [comment]
Since my language server has been implemented using both O# and my own language server framework, I can provide a comparison. Based on my language server framework, the performance improvement after AOT compilation is very significant. It is highly suitable for developers who want to enhance the performance of their language server.

**Comment by JoeRobich** [comment]
I think it is time to close this issue out. This repo is as active as the community makes it. I am happy to facilitate releases and help guide community members who wish to contribute.

**Comment by JustinGrote** [comment]
Sorry to necro the thread but Rosyln has [moved their LanguageServer](https://github.com/dotnet/roslyn/tree/main/src/LanguageServer) and there's a lot of development, I don't see any correlating releases yet though.
