### ISSUE TITLE
IDidChangeConfigurationHandler fires but DidChangeConfigurationParams is always empty

### ISSUE THREAD

**Issue by ajaybhargavb** [OmniSharp/csharp-language-server-protocol#205]
The [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeConfiguration) says the params should contain the actual changed settings but when I inspect the params, it is always empty for any change in settings.
Am I missing something?

**Comment by david-driscoll** [comment]
what I've discovered (if you hadn't already figured out) is that if the configuration payload is null/empty the spec expects you to go query for the data.

See this issue for a little more detail:  https://github.com/Microsoft/vscode-languageserver-node/issues/380

You have to support both technically speaking because of the different protocol versions.
