### ISSUE TITLE
Undocumented binary breaking change TextDocumentEdit.set_Edits

### ISSUE THREAD

**Issue by SeeminglyScience** [OmniSharp/csharp-language-server-protocol#231]
The property `TextDocumentEdit.Edits` was changed to be of type `TextEditCollection` instead of `Collection<TextEdit>` in #186.

So for example if a method setting the property in a library that was built targeting `0.14.0` is jitted in an appdomain where `0.16.0` is already loaded, a `MissingMethodException` is thrown.

Not really suggesting anything be done about it other than maybe document it in the releases. Mostly just creating this issue as an FYI.

**Comment by david-driscoll** [comment]
@SeeminglyScience so firstly apologies, we try to avoid making breaking changes, sometimes however the spec just doesn't let us avoid that.  
*  That change actually seems non-sensicle (cause it just wraps `Container<>` anyway) I have a feeling that was made from the moment the spec lost all the history of the original markdown, and I had to comb over the spec meticulously.
* Generally I try to keep the changes additive and non-breaking as best I can.
* This is the reason I've avoid making a v1 at the moment, because there can still be breaking changes happen.  I think with the next version of the spec (16) I'll probably look at setting the major version.

Second I did not know that there were extensions for the powershell tooling out there that exist like that, that is amazing! 👏 

Couple small notes: There is the new change incoming with `DocumentUri` that is a similar breaking change, but it will help solve the issues around how vscode handles uris for all consumers.
