### ISSUE TITLE
Single or multithread ?

### ISSUE THREAD

**Issue by mikkleini** [OmniSharp/csharp-language-server-protocol#249]
I've used this library for a while now but I can't seem to find definite answer if the requests come to handlers from single thread or from multiple threads? In other words - can there be multiple requests at the same time? LSP documentation hints it can. But how is Omnisharp implementation done?

Basically - should I make my code thread safe or not? In the example code and in Microsoft language server implementations I see some concurrent collection objects, but it seems to work with regular collections just as fine. I would like to use observable collections to react to text document changes with events but I'm not sure it's okay approach.

I don't have much experience with services and async programming so forgive if it's a stupid question.

**Comment by david-driscoll** [comment]
@mikkleini this is not a stupid question (I have a rule there are no stupid questions, just questions that get asked too many times, this is not one).

So you are correct the spec is pretty vague when it comes to parallelism. (See: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#request-notification-and-response-ordering )
> Request, Notification and Response ordering
Responses to requests should be sent in roughly the same order as the requests appear on the server or client side. So for example if a server receives a textDocument/completion request and then a textDocument/signatureHelp request it will usually first return the response for the textDocument/completion and then the response for textDocument/signatureHelp.
> 
> However, the server may decide to use a parallel execution strategy and may wish to return responses in a different order than the requests were received. The server may do so as long as this reordering doesn’t affect the correctness of the responses. For example, reordering the result of textDocument/completion and textDocument/signatureHelp is allowed, as these each of these requests usually won’t affect the output of the other. On the other hand, the server most likely should not reorder textDocument/definition and textDocument/rename requests, since the executing the latter may affect the result of the former.

What we have done is make a decision that there are some requests that are "serial" requests, in that they cannot be parallelized because it would "change the state of the server".  And then there are requests that are "parallel" in that they can run concurrently together.

Serial requests include things like `textDocument/didChange` or `textDocument/didOpen` (and most of the text change operations).
Parallel requests include things like `textDocument/hover` or `textDocument/declaration` and more.

See: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#implementation-considerations
>if a server detects a state change that invalidates the result of a request in execution the server can error these requests with ContentModified. If clients receive a ContentModified error, it generally should not show it in the UI for the end-user. Clients can resend the request if appropriate.

In the latest unreleased version we are also implementing support for the `ContentModified` result type (this a derived RequestCancelled` response). So this behavior will cancel any pending parallel operations if a new serial operation (text change) comes through.  This is behind a feature flag that you can disable if you want to. `ContentModifiedSupport` (I think).

Now to your specific question:

> Basically - should I make my code thread safe or not? In the example code and in Microsoft language server implementations I see some concurrent collection objects, but it seems to work with regular collections just as fine. I would like to use observable collections to react to text document changes with events but I'm not sure it's okay approach.

With the current implementation you should never see concurrent threads for "write" (Serial) operations (didchange, rename, etc).  You could however have multiple threads "reading" (Parallel) at the same time (for completions and such).  

What this means is that if your server needs to do some calculations during the first read, or a resolve read (codelens, completion and document link all support the ability to resolve for more data), you might want to add a lock of a semaphore as those parts get built, otherwise you might encounter a bad state.

However parts of the internals are all implemented in system.reactive observables (not ObservableCollection itself).  If you want to have safer observable collections and you like System.Reactive I totally recommend [DynamicData](https://github.com/reactiveui/DynamicData) the `ObservableCache` and `ObservableList` gives you the ability to turn a `IObservable<T>` into a list that updates automatically as the source observable changes.

**Comment by mikkleini** [comment]
@david-driscoll thanks for explanation. I need to think how to handle thread-safety at my side. But how about the Omnisharp's ability to take push request from concurrent threads? E.g. PublishDiagnosticsExtensions.PublishDiagnostics function?

**Comment by david-driscoll** [comment]
for sending requests and notifications (diagnostics is just a notification) they go into a thread safe queue (and if you find an issue here I'd love to know about it) and then that queue is drained on a different thread in order the items were queued.  

So if you queue 100 diagnostics from different threads the only thing that might vary is the order they land in the queue, but they should all make it.  Keep in mind with diagnostics, any diagnostics for a specific document are emptied when you send another set through, so make sure you gather all the diagnostics for a specific document in the same place.

**Comment by mikkleini** [comment]
I tried few things like BlockingCollection, custom "two lists and concurrent queue syncing the changes between them" and other tricks, but eventually I sticked to DynamicData because it seemed to have all that I need. Good suggestion @david-driscoll. I haven't looked under the hood of DynamicData so I'm still bit hesitant how reliable it is, but I did some parallel unit tests and there were no issues.

Basically my solution is checking special aspects of the code. Each text document class performs parsing when changes occur and puts the parsed info to own DynamicData.SourceList. In parallel, the diagnostic task fetches that info from the IObservableLists which are created from the documents SourceLists. Seems to work quite well. First I thought that I'll make the parsing also asynchronous but since it's done on incremental changes then it's fast enough to be done directly in the change handler.

Basically I got answers to my questions and even more. From my point of view this topic can be closed.

**Comment by david-driscoll** [comment]
👍 glad you got what you needed! 

If you have dynamic data questions there is a slack channel available on the [reactivex slack](https://reactiveui.net/slack)

**Comment by mikkleini** [comment]
@david-driscoll - I actually have to come back to this topic and I would appreciate some advice. The problem is that not everything can be analyzed in content change handler. Some things needs to be analyzed in the read-only "parallel" requests.

For example, one of the code actions needs to do regex search. Even though content string is immutable, I would have to do several accesses to it - first the search, then parsing line breaks to get line number, etc. As I understand it's not safe, because the "serial" requests can modify that string anytime.

Checking cancellation token wouldn't help because it's not checked at every line and locking would still be needed. It looks like I need to take snapshots of content before analysis. On the other hand, it feels very wasteful to have several copies of same document. Is there any better way?

**Comment by mikkleini** [comment]
Actually, I believe I found an answer:
I store the documents content in string. When document gets updated incrementally, I call this:

`Content = Content.Remove(index, oldLength).Insert(index, newContent);`

This line however causes creation of (two) new string(s) in memory. One of them and the old content are left for GC. So there's "waste" anyway which is just too hard to avoid. And to do analysis in another thread on the content, it would be enough to just take a reference of "Content" (e.g. `string temp = Content;`) and that's it. The string is immutable so I don't have to worry about the changes.
