### ISSUE TITLE
Support for a response body on "workspace/executeCommand"

### ISSUE THREAD

**Issue by anthony-c-martin** [OmniSharp/csharp-language-server-protocol#308]
If I'm reading the LSP spec correctly, seems like it should be possible to supply a response body to the "workspace/executeCommand" message (see [here](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_executeCommand)).

The `ExecuteCommandParams` class implements `IRequest` which only allows for a handler function to return `Unit`, so I wasn't able to find a way to return a response body.

**Comment by david-driscoll** [comment]
While the spec says you can return something, what would you return there?  You'd be coupling the client to the server at that point.

I think this may be doable without changes, by introducing a custom interface, however I'll add a test to validate that for sure.

**Comment by david-driscoll** [comment]
I lied it might not be possible today, but I'm going to add some logic to help with that.

**Comment by anthony-c-martin** [comment]
It seemed to me like the intention of this LSP feature (again, I may well be misunderstanding!) was to provide some sort of custom pre-agreed-upon contract between client and server - at which point yes there would be coupling, but that already seems to be the case in the request contract.

In my scenario, I'd like to be able to send a command to compile and receive a compiled document in return. Since I have the communication channel from client to server open already, it would be nice if I could use it to do something ad-hoc like this rather than coming up a separate mechanism.

**Comment by anthony-c-martin** [comment]
> I think this may be doable without changes, by introducing a custom interface, however I'll add a test to validate that for sure.

I'm interested to see that! I had a go at implementing my own version of `ExecuteCommandParams` which extends `IRequest<object>`, but wasn't able to access the `[Optional]` attribute as I think it's an internal class

**Comment by david-driscoll** [comment]
Yeah the spec is pretty open ended, I've tried to strive towards best compatibility for general purpose handlers, so I picked a side on this one.

**Comment by david-driscoll** [comment]
@anthony-c-martin I got the changes together, there was some work to get the custom handlers working, but this is something I've intended to support, it just wasn't... 😄 

https://github.com/OmniSharp/csharp-language-server-protocol/pull/309

This [unit test](https://github.com/OmniSharp/csharp-language-server-protocol/pull/309/files#diff-bc5c8ecfc615f490098903e6fe1463ebR75) demonstrates execute handler specifically. 

However because we special case command execution, so that you can implement multiple handlers and not worry about routing, there is an interface that must be implemented `IExecuteCommandParams` along with your handler should implement `IRegistration<ExecuteCommandRegistrationOptions>`.

**Comment by anthony-c-martin** [comment]
That's awesome, thank you!
