### ISSUE TITLE
Workspace/executeCommand request - return a value

### ISSUE THREAD

**Issue by nenadTod** [OmniSharp/csharp-language-server-protocol#370]
Hi! 
I am trying to figure out how to return a value when handling a Workspace/ExecuteCommand request. If I am reading this right, the LSP protocol specifies that [return value can be any | null](https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand).

I have investigated a bit. I found that [IExecuteCommand](https://github.com/OmniSharp/csharp-language-server-protocol/blob/72206aff40eb5be8603b19b5758dc101289d7a7c/src/Protocol/Workspace/IExecuteCommandHandler.cs#L20) implicitly extends [MediatR.IRequestHandler<T>](https://github.com/jbogard/MediatR/blob/af6323735fe7f574a8887d4d6ac09f69b0b50d53/src/MediatR/IRequestHandler.cs#L28) - meaning that OmniSharps' LSP ExecuteCommand can't return anything by design. 
 
Is there any other way to return an answer to the client that sent the request? How should we approach this problem?

Thanks in advance!

**Comment by david-driscoll** [comment]
This was actually solved via #308 

Right now the execute command does not return anything, for both backwards compatibility reasons and because there is no return type.  Due to how this can couple your client and server together.

However you can implement your own custom command handler as demonstrated by [this unit test](https://github.com/OmniSharp/csharp-language-server-protocol/blob/72206aff40eb5be8603b19b5758dc101289d7a7c/test/Lsp.Tests/Integration/OverrideHandlerTests.cs#L75-L110) where you can then define whatever return type you would like.

This is something I should probably bake into the library so I'm going to leave this open so I don't forget.

**Comment by nenadTod** [comment]
Great, thank you very much! We'll look into that.
