### ISSUE TITLE
Busy waiting

### ISSUE THREAD

**Issue by Lercher** [OmniSharp/csharp-language-server-protocol#4]
in src\JsonRpc\OutputHandler.cs there is a tight loop plus a Delay/Sleep() which looks quite inefficient to me. I've prepared a pull request for this, you might want to look into.

There is a similar one in src\JsonRpc\InputHandler.cs at `private async void ProcessRequestQueue()`, but I'm afraid I'm to dumb to understand, what is done there. So could you please evaluate, if you could probably change the  `ConcurrentQueue<>` to a `BlockingCollection<>` plus a `CancellationTokenSource`here as well?

Thanks
Martin

**Comment by david-driscoll** [comment]
The call to `Delay` / `Sleep` only happens when the Queue has been drained.  If there are still pending requests / responses in the queue then there will no wait.  The intent is to avoid having a few threads constantly running in circles waiting for events to be received.  If there is a better implementation, I'm totally open to using alternatives.

------

The intent in `ProcessRequestQueue` is to avoid processing requests strictly in serial.  `IRequestProcessIdentifier` allows the implementer to decide what can be done in parallel, and what must be done in serial.

For example a text change event will almost always be blocking, as it will affect any of the next requests that happen.  However something like autocomplete, or signature help are not bound in that way.  This way those requests can be served back to the editor as fast as possible.

Strictly speaking the protocol says all requests must respond in order received, but this allows an implementer the ability to bypass some of that for endpoints that don't affect the overall solution.

Note: I haven't started a real integration some of these implementations will likely change.

**Comment by Lercher** [comment]
(1) on "The call to ...": I only agree partly. The queue is almost always empty or seldom contains one item, so assuming a configured delay of 50ms, the old consumer thread burns some cycles, only to check the queue is empty, waits 50ms, repeat and drains the battery. Now assume a unit of work arrives in the middle of the 50ms delay, then for 25ms plus thread switching time nothing happens, except delay. The new code should not burn CPU cycles, if there is nothing to do. And it has no lag besides task switching time. If the queue is longer than one item, all work is done at top speed, just as before. 

Thanks for accepting my fix.

**Comment by Lercher** [comment]
(2) on "The intent in ...": Before I feel confident enough to offer you a change, could you please verify/comment on these statements:
* In general: all units of work are scheduled in parallel and started in parallel, except ...
* ... an item in `_queue` marked as `Serial` waits for all previously scheduled units of work to be finished, plus ...
* ... processing the queue items blocks on the finishing of such a `Serial` item.

If all of this is true, I propose this algorithm, assuming `item.start` returns something awaitable:
````
let waitables = new list of waitable objects
loop forever
  let item = blocking dequeue 
  if item is Serial then 
    wait-for-all waitables
    waitables.clear
    wait-for item.start
  else
    waitables.add item.start
````

**Comment by Lercher** [comment]
(2) it's now working on my machine, but I think it needs more testing.

**Comment by david-driscoll** [comment]
However that will breakdown if the queue is empty, and there has been no serial item.  I haven't had enough tests in that specific area to really say for sure what would work and what wouldn't yet.

**Comment by Lercher** [comment]
Yes, a memory leak, you are right. However I don't think it would be a breakdown:. The q sits on it's blocking dequeue, all tasks are started but no one is waiting for then. I'm preparing a fix for that: in the `else` clause there could be some housekeeping that removes the completed tasks from the waitables list. That would not be perfect, but performant.

But: This leads to another question: Could you please make up your mind, how an item's task exception could be handled (i.e. here, in the InputHandler and in the OutputHandler)? I guess they are ignored now, aren't they, and this is an opportunity for trouble? I suggest an error service (IHandleExceptions : void Post(int id, Exception)) injected to all relevant components.

Regading tests. In my branch on that https://github.com/Lercher/csharp-language-server-protocol/tree/inputhandler-refactoring, I've factored out the scheduling component and added some tests for it.

**Comment by Lercher** [comment]
Done. It's not perfect, if many items would be added simultaneously, there can be a memory peek, but it drops quickly on the next add/dequeue cycle. So an IDE exercising the language server in a "normal" way would keep the list short. If it turns out to be problematic, we could reduce the infinite timeout on the dequeue operation to something reasonable to do the housekeeping on idle times.

**Comment by Lercher** [comment]
An additional issue of the original code was, that with the typical pauses, a language-server client makes, the first two long-running parallel work items and probably some more afterwards would effectively be serialized, depending on the timing of pauses and handler processing time.

The pull request (#11) is prepared now, I did some integration testing with vscode and I'm confident enough to publish it. Best regards, Martin.

**Comment by Lercher** [comment]
Merged. Closed.
