### ISSUE TITLE
Language server bits aren't strong name signed.

### ISSUE THREAD

**Issue by NTaylorMullen** [OmniSharp/csharp-language-server-protocol#94]
Doing some investigations on the Microsoft ASP.NET team and MediatR + the JsonRpc + Protocol + Server bits not being storng name signed is a blocker for us. 

Is there any specific reason as to why things aren't strong name signed?

**Comment by tintoy** [comment]
Not that I'm aware of. @david-driscoll?

**Comment by david-driscoll** [comment]
Mainly because strong naming is contagious, and generally a contentious issue.  Also I doubt MediatR will ever be strong named (re: https://github.com/jbogard/MediatR/issues/86)

Strictly speaking is it required for your solutions?  (Just trying to gather the reasons)

iirc it's because you can't grant internal access from a strong named assembly to a unsigned assembly.

I would be open to updating the build IL merges in MediatR, and is strong named, as I don't generally expect anyone to bring in packages that add MediatR pipelines or anything.  (MediatR is a means to an end).

**Comment by david-driscoll** [comment]
thinking about ILMerge and .net core... hell it might be easier to submodule in MediatR and just include the source files.

**Comment by david-driscoll** [comment]
Beta packages should now be strong named https://www.myget.org/feed/Packages/omnisharp

I'm going to work through any existing spec updates (looks like code actions is new) and then release a proper version to nuget.

**Comment by NTaylorMullen** [comment]
The packages are beautiful. Consuming them now ❤️
